Migrate `ballerina/ldap` module
ballerina-platform/module-ballerina-ldap pull request #2
Opened 2020-08-21 07:06 UTC by ldclakmal

## Purpose
This PR migrate the implementation of `ballerina/ldap` module including the integration tests with the Git history.

Related to https://github.com/ballerina-platform/ballerina-lang/issues/25050

2020-08-21 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/module-ballerina-ldap?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/module-ballerina-ldap?pullRequest=2) before we can accept your contribution.<br/>**18** out of **20** committers have signed the CLA.<br/><br/>:white_check_mark: Kishanthan<br/>:white_check_mark: ldclakmal<br/>:white_check_mark: hemikak<br/>:white_check_mark: SupunS<br/>:white_check_mark: wggihan<br/>:white_check_mark: hevayo<br/>:white_check_mark: rasika<br/>:white_check_mark: aashikam<br/>:white_check_mark: ThisaruGuruge<br/>:white_check_mark: rdhananjaya<br/>:white_check_mark: kalaiyarasiganeshalingam<br/>:white_check_mark: pubudu91<br/>:white_check_mark: Bhashinee<br/>:white_check_mark: riyafa<br/>:white_check_mark: chamil321<br/>:white_check_mark: warunalakshitha<br/>:white_check_mark: chiranSachintha<br/>:white_check_mark: praneesha<br/>:x: Manuri<br/>:x: Kalaiyarasi<br/><hr/>**Kalaiyarasi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/module-ballerina-ldap?pullRequest=2) it.</sub>

2020-08-24 07:07 UTC, BuddhiWathsala requested changes

2020-08-24 07:07 UTC, BuddhiWathsala commented on gradle/javaProject.gradle
> +/*
Do we need this configuration file?

2020-08-24 07:07 UTC, BuddhiWathsala commented on ldap-ballerina/build.gradle
> +    ldapBallerinaJar
```suggestion
```

2020-08-24 07:07 UTC, BuddhiWathsala commented on ldap-ballerina/build.gradle
> +    externalJars (group: 'org.apache.directory.server', name: 'apacheds-all', version: '2.0.0-M24') {
Shall we parameterize this version as `${ballerinaLangVersion}`?

2020-08-27 15:38 UTC, BuddhiWathsala commented
@ldclakmal, don't we need this `apacheds-all-2.0.0-M24.jar` dependency anymore?

2020-08-27 16:23 UTC, ldclakmal commented
@BuddhiWathsala No. It was used only for a Java test class. Since I removed that with docker image, it is no longer needed.

2020-08-28 04:15 UTC, BuddhiWathsala approved these changes

2020-08-28 04:15 UTC, merged